name: mynav
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Localization https://github.com/dart-lang/intl
  intl: ^0.16.1
  # Toast插件 https://github.com/OpenFlutter/flutter_oktoast
  oktoast: ^2.3.2
  # 网络库 https://github.com/flutterchina/dio
  dio: ^3.0.9
  # https://github.com/ReactiveX/rxdart
  rxdart: ^0.24.1
  # Dart 常用工具类库 https://github.com/Sky24n/common_utils
  common_utils: ^1.2.1
  # Flutter 常用工具类库 https://github.com/Sky24n/flustars
  flustars: ^0.3.2
  # Flutter 轮播图 https://github.com/best-flutter/flutter_swiper
  flutter_swiper: ^1.1.6
  # 启动URL的插件 https://github.com/flutter/plugins/tree/master/packages/url_launcher
  url_launcher: ^5.4.10
  # 图片选择插件 https://github.com/flutter/plugins/tree/master/packages/image_picker
  image_picker: 0.6.7+1
  # 侧滑删除 https://github.com/letsar/flutter_slidable
  flutter_slidable: ^0.5.4
  # WebView插件 https://github.com/flutter/plugins/tree/master/packages/webview_flutter
  webview_flutter: 0.3.22+1
  # 处理键盘事件 https://github.com/diegoveloper/flutter_keyboard_actions
  keyboard_actions: ^3.2.1+1
  # 列表悬浮头 https://github.com/fluttercommunity/flutter_sticky_headers
  sticky_headers: ^0.1.8+1
  # 城市选择列表 https://github.com/flutterchina/azlistview
  azlistview: ^0.1.2
  # 手势识别 https://github.com/aleksanderwozniak/simple_gesture_detector
  simple_gesture_detector: ^0.1.4
  # 路由框架 https://github.com/theyakka/fluro
  fluro: ^1.6.3
  # 图片缓存 https://github.com/renefloor/flutter_cached_network_image
  cached_network_image: ^2.2.0+1
  # 格式化String https://github.com/Naddiseo/dart-sprintf
  sprintf: ^4.0.2
  # 状态管理 https://github.com/rrousselGit/provider
  provider: ^4.1.3
  # # 扫码 https://github.com/apptreesoftware/flutter_barcode_reader
  # barcode_scan: 3.0.1
  # 高德2D地图插件 https://github.com/simplezhli/flutter_2d_amap
  flutter_screenutil: ^1.1.0
  pull_to_refresh: ^1.5.8
  shared_preferences: ^0.5.7+3
  cookie_jar: ^1.0.1
  path_provider: ^1.6.10
  device_info: ^0.4.2+4
  package_info: ^0.4.1
  sliding_up_panel: ^1.0.2
  permission_handler: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # 集成测试
  flutter_driver:
    sdk: flutter
  # 单元测试
  test: ^1.14.4
  intl_translation: ^0.17.9

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  assets:
    - assets/data/
    - assets/images/
    - assets/images/home/
    - assets/images/login/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: RobotoThin
      fonts:
        - asset: assets/fonts/Roboto-Thin.ttf
